### ISSUE TITLE
Package working at all?

### ISSUE THREAD

**Issue by niklassiemer** [conda-forge/pyiron_continuum-feedstock#7]
I am kind of confused looking at the recipe here:
https://github.com/conda-forge/pyiron_continuum-feedstock/blob/e3013431d764be6e4029cb5e981ff49318cc0ab5/recipe/meta.yaml#L9
should this not link to `pyiron-continuum` instead of `pyiron_continuum` on PyPI?

**Comment by jan-janssen** [comment]
The automated pull requests work, so I guess it is fine https://github.com/conda-forge/pyiron_continuum-feedstock/pull/4
